root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/bin/pyra"
  pre_cmd = []
  cmd = "make pyra_build_dev"
  post_cmd = []
  delay = 500
  exclude_dir = ["bin", "view/assets", "public", "tmp", "vendor", "testdata", "node_modules"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  # include_ext = ["go", "tpl", "tmpl", "html", "templ"]
  include_ext = ["go", "html"]
  include_file = []
  kill_delay = "3s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = false

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
