root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "./tmp/bin/pyra"
  cmd = "make pyra_build_dev"
  delay = 500
  exclude_dir = ["bin", "view/assets", "public", "tmp", "vendor", "testdata", "node_modules"]
  exclude_file = []
  # include_ext = ["go", "tpl", "tmpl", "html", "templ"]
  include_ext = ["go", "html"]
  include_file = []
  kill_delay = "1s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = false

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
